// Generated by purs bundle 0.13.6
var PS = {};
(function(exports) {
  "use strict";

  exports.getVariable = s => () => context.getVariable(s)
  exports.setVariable = s => v => () => context.setVariable(s,v)
  exports.print = s => () => print(s)
})(PS["Apigee"] = PS["Apigee"] || {});
(function($PS) {
  // Generated by purs version 0.13.6
  "use strict";
  $PS["Apigee"] = $PS["Apigee"] || {};
  var exports = $PS["Apigee"];
  var $foreign = $PS["Apigee"];
  exports["getVariable"] = $foreign.getVariable;
  exports["setVariable"] = $foreign.setVariable;
  exports["print"] = $foreign.print;
})(PS);
(function($PS) {
  // Generated by purs version 0.13.6
  "use strict";
  $PS["Pure1"] = $PS["Pure1"] || {};
  var exports = $PS["Pure1"];
  var Apigee = $PS["Apigee"];                
  var main = function __do() {
      Apigee.setVariable("q")("w")();
      var a = Apigee.getVariable("request.queryparam.a")();
      var b = Apigee.getVariable("q")();
      return Apigee.print(a + (" " + b))();
  };
  exports["main"] = main;
})(PS);
PS["Pure1"].main();